- name: Bootstrap development environment
  hosts: localhost

  tasks:
  - name: Add neovim unstable apt repository
    become: yes
    ansible.builtin.apt_repository:
      repo: ppa:neovim-ppa/unstable
  - name: Update and upgrade apt packages
    become: true
    apt:
      update_cache: yes
      upgrade: 'yes'
  - name: Install plc-cli
    ansible.builtin.pip:
      name: pls-cli
  - name: Install packages with apt
    become: yes
    ansible.builtin.apt:
      name:
        - zsh
        - neovim
        - git
        - ripgrep
        - tmux
        - exa
        - fzf
        - ncal
      state: present
  - name: Clone nvim config
    ansible.builtin.git:
      repo: 'https://github.com/weirdmann/nvim'
      dest: '~/.config/nvim' 
      clone: yes

